[package]
name = "shared"
version = "0.1.0"
edition = "2024"
authors = ["Zain Ahmed <zainahmed1559@gmail.com>"]
license = "MIT OR Apache-2.0"


[dependencies]
zerocopy = { version = "0.8.27", features = ["derive"] }
